#!/usr/bin/env bash
#
# assemble.sh — build a context bundle for a given scope.
#
# Usage:
#   ./assemble.sh <scope> [--full] [--writing]
#
#   <scope>      scope name, case-insensitive (e.g. acme, writing, personal)
#   --full       also include on-demand memory: decisions, latest log + rollup
#   --writing    also include global/style.md (load when the task is writing)
#
# Tiers (what gets loaded):
#   1. ALWAYS        global/identity.md, global/preferences.md
#   2. SCOPE always  <scope>/facts.md, <scope>/people.md, <scope>/workflow.md
#   3. ON-DEMAND     <scope>/decisions.md, latest <scope>/log/*, <scope>/log/_rollup.md
#                    global/style.md
#
# Prints the bundle to stdout (so a router can capture it). A manifest with an
# approximate token count goes to stderr.

set -euo pipefail

ROOT="${GRANDMA_HOME:-$HOME/.grandma}"   # the user's private memory home

# ---- args ----
SCOPE=""
FULL=0
WRITING=0
for arg in "$@"; do
  case "$arg" in
    --full)    FULL=1 ;;
    --writing) WRITING=1 ;;
    -*)        echo "unknown flag: $arg" >&2; exit 2 ;;
    *)         SCOPE="$arg" ;;
  esac
done

if [[ -z "$SCOPE" ]]; then
  echo "usage: $(basename "$0") <scope> [--full] [--writing]" >&2
  echo "scopes:" >&2
  for d in "$ROOT"/*/; do
    name="$(basename "$d")"
    [[ "$name" == "global" || "$name" == ".git" ]] && continue
    echo "  - $name" >&2
  done
  exit 2
fi

# ---- resolve scope dir (case-insensitive), excluding global ----
SCOPE_DIR=""
for d in "$ROOT"/*/; do
  name="$(basename "$d")"
  [[ "$name" == "global" ]] && continue
  if [[ "$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]')" == "$(printf '%s' "$SCOPE" | tr '[:upper:]' '[:lower:]')" ]]; then
    SCOPE_DIR="${d%/}"
    break
  fi
done

if [[ -z "$SCOPE_DIR" ]]; then
  echo "error: no scope matching '$SCOPE' under $ROOT" >&2
  exit 1
fi

# ---- collect files in tier order ----
FILES=()
add() { if [[ -f "$1" ]]; then FILES+=("$1"); fi; }

# tier 1: always
add "$ROOT/global/identity.md"
add "$ROOT/global/preferences.md"

# tier 2: all scope root .md files except decisions.md (that is on-demand via --full)
for f in "$SCOPE_DIR"/*.md; do
  [[ -f "$f" ]] || continue
  [[ "$(basename "$f")" == "decisions.md" ]] && continue
  add "$f"
done

# tier 3: on-demand
if [[ "$WRITING" -eq 1 || "$FULL" -eq 1 ]]; then
  add "$ROOT/global/style.md"
fi
if [[ "$FULL" -eq 1 ]]; then
  add "$SCOPE_DIR/decisions.md"
  add "$SCOPE_DIR/log/_rollup.md"
  # latest dated log (YYYY-MM-DD sorts lexically; the glob expands in sorted order, so the
  # last non-rollup entry is the newest). No `ls | grep` — safe with odd filenames.
  if [[ -d "$SCOPE_DIR/log" ]]; then
    latest_log=""
    for _lg in "$SCOPE_DIR"/log/*.md; do
      [[ -e "$_lg" ]] || continue
      [[ "$(basename "$_lg")" == "_rollup.md" ]] && continue
      latest_log="$_lg"
    done
    add "$latest_log"
  fi
fi

# ---- emit bundle ----
scope_name="$(basename "$SCOPE_DIR")"
printf '===== MEMORY BUNDLE: scope=%s =====\n' "$scope_name"
printf 'Generated by assemble.sh. Files included in load-priority order.\n\n'

total_chars=0
for f in "${FILES[@]}"; do
  rel="${f#"$ROOT"/}"
  printf -- '----- BEGIN %s -----\n' "$rel"
  cat "$f"
  printf -- '\n----- END %s -----\n\n' "$rel"
  c=$(wc -c < "$f")
  total_chars=$((total_chars + c))
done

# ---- manifest to stderr ----
{
  printf 'bundle manifest (scope=%s, full=%s, writing=%s):\n' "$scope_name" "$FULL" "$WRITING"
  for f in "${FILES[@]}"; do printf '  + %s\n' "${f#"$ROOT"/}"; done
  printf '  ~%d chars, ~%d tokens\n' "$total_chars" "$((total_chars / 4))"
} >&2
